version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\MIG.HomeAutomation.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - MIG.HomeAutomation.Tests/bin/Debug/MIG.HomeAutomation.Tests.dll
after_test:
  - ps: .\MIG.HomeAutomation\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: MIG nupkg
    type: NuGetPackage
deploy:
  - provider: GitHub
    auth_token:
      secure:  1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: ER771ujBnbfc/o+8QyM3XZInr0JyFfv3GIdDyQZfZtNUuCCkDn4cFEc1ZJGCYkpt
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

