version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\MIG.HomeAutomation.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - MIG.HomeAutomation.Tests/bin/Debug/MIG.HomeAutomation.Tests.dll
after_test:
  - ps: .\MIG.HomeAutomation\nuget_pack.ps1
artifacts:
  - path: '*.nupkg'
    name: MIG nupkg
deploy:
  - provider: GitHub
    auth_token:
      secure: an604bliUDgeH6X8mSIUViIWgeDYHQr695TrU7S6O7nhSavBBdflYyKNgIBoaew2
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: xe7KBrpDVPQYOr4XpJNPs2/9vdT5lO/qV5z8Qrv3yXWd6kQScl3UfB5WaF7olbfy
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
